### 로그인한 유저가 거주하는 지역의 현재 날씨 GET
GET http://localhost:8080/weather/647226b973194d41c6fb0013

### 유저가 거주하는 지역의 현재 날씨 DB에 생성
GET http://localhost:8080/weather/647226b973194d41c6fb0013/create

### 유저가 거주하는 지역의 현재 날씨 DB에 저장
GET http://localhost:8080/weather/647226b973194d41c6fb0013/save

### 유저가 거주하는 지역의 현재 날씨 DB에서 가져옴
GET http://localhost:8080/weather/647f58c133f495fdc5fd7477/get