### DHT22의 온습도 센서의 온도값 GET
GET http://localhost:8080/dht/temperature

### DHT22의 온습도 센서의 습도값 GET
GET http://localhost:8080/dht/humidity

### DHT22의 온습도 센서의 습도값 GET
GET http://localhost:8080/dht/648205e1971e183f0afe53d0

### DHT22의 온습도 센서의 습도값 change
GET http://localhost:8080/dht/648205e1971e183f0afe53d0/change